### ISSUE TITLE
Add login/oAuth flow

### ISSUE THREAD

**Issue by ronaldmansveld** [thewca/wca-live-archived#11]
Add pages and services that allow the user to login using WCA oAuth

**Comment by coder13** [comment]
What's the flow we have chosen?

> use presses login button
> sends a get request to /auth/login (or something)
> server handles the oauth flow, redirects back to the client
> server grabs /api/v0/me to determine if logged in
> now logged in

This is how my apps work, is this what we should do?

**Comment by ronaldmansveld** [comment]
Hmm, but how would the server know which user to log in?

I'm not that well versed in OAuth in general (as I've always worked on systems with proprietary logins), but it seems to me that we have to communicate which user wants to login, and ask for their password etc.

Maybe this should all be handled client-side? The client can then pass the received token into the Authorization header, which the server can then use if it has to communicate with the original WCA api.

Maybe @jonatanklosko can shine some light on this, as he has made apps that use the WCA login before.

**Comment by coder13** [comment]
Once logged in, express creates a session and we store that sessionId in a cookie. 

Definitely also want to hear Jonatan's thoughts.

Edit: I just realized this doesn't follow a RESTful stateless design, but this API is supposed to be directly tied into the frontend, we're not creating a stateless api for other apps to use.

**Comment by ronaldmansveld** [comment]
I personally wouldn't store that data in a cookie. It's too focussed on web, and the API should be unaware if it's talking to a web-based client, or a native android/iOS app. Better to return the token in a JSON response, and let the client deal with where it's best for them to store that information.

I'm still not convinced about having the server logging the user in, mainly because the server wouldn't know *which* user to log in. As such I feel that the login flow should happen on the client. The client can then inform the server what token to use to communicate with the WCA API server when needed.
The token will be added to all requests in the Authorization header, so the API can remain stateless, as it should.

Also, by having the client handle the token itself (instead of using a cookie from the server), the app can make smart decisions based on login state, such as whether or not to display the the edit parts of the screens.
With cookies this is still possible, but via a more roundabout way, where the code has to read and parse the cookie. This means the cookie can not be HTTP only, which increases the chance of the token leaking out.

**Comment by jonatanklosko** [comment]
@ronaldmansveld
- client-side OAuth is generally less secure and should be used only when there's no server at all (at least for my knowledge). The main flaw of this flow is the fact that access token resides in the browser, thus being more open to stealing. On the other hand, if we are going to pass the token to the client anyway to make WCA requests directly, then I'm not sure how helpful it is to do server-side OAuth... @jfly, @coder13?
- what do you mean by the server not knowing _which_ user to log in?

Still thinkings about the best way. We certainly need to know the answers for two questions:
1. Do we want to redirect to WCA authorization or open it in a new window? (I mentioned it in the email, and redirecting seems just fine to me in this case).
2. Are we sure that we want to make WCA API calls directly from the client-side app?

**Comment by ronaldmansveld** [comment]
@jonatanklosko : What I mean is: If the login is handled by the server instead of the client, I have to provide the login-details (username/WcaId and password) to the server, or the server wouldn't know as which user to login. (The server wouldn't know to send my or your login-details to the oauth system, unless I tell the server my or your details) As far as I know, part of oauth is that the user then has to give the original system (in this case WCA) permission that the using system (in this case WCA Live) can use his/her credentials. How would that work when the login is done by the server?

I do think it's valuable that the client can contact the WCA API directly for data that is already available there. I don't think there's much added value in replicating or proxying that data through the WCA Live API.

**Comment by jonatanklosko** [comment]
Hmm, I don't quite get the credentials thing you presented =) You wouldn't enter those within wca-live, right? The flow is that you when a user clicks _Sign in (with WCA)_ you immediately redirect him to the WCA website, where he signs in (unless already signed in) and then sees the Authorization page, where he can either allow or dismiss wca-live to use his data. When he decides to allow it, then the WCA website generates an access token linked to this user. Then, depending on the flow you use (i.e. _implicit_ for client side or _code_ for server side), the flow differs. Finally, either client or server has the access token (and *only* the access token, without any credentials). Keeping in mind that access token is linked with a WCA user account, you can make an authorized request to the WCA website's `/api/v0/me` endpoint to get all the user information. So whoever has the access token, also can know the user identity.

Sorry if I'm describing things you know well, but I just want to find the point in which I don't get your point of confusion =) Let me know if anything of the above doesn't make sense!

**Comment by ronaldmansveld** [comment]
Ahhhh, now it makes more sense. All this time when you were talking about the server handling the login, it sounded to me that the server was making the actual login request. Hence my understanding that server had to know as who to login, and the server having to know the username and password to do the actual login ;)

In that case it's indeed a question of  whether or not the client will access the regular WCA API directly or not if the token should be on the server or on the client.

**Comment by jonatanklosko** [comment]
Note: it's not even a question of whether the client will access WCA API or not. It's a question of what endpoints it's gonna need. The access token is not necessary for public stuff (e.g. PBs for the given WCA ID, WRs/CRs/NRs [to be implemented], other public stuff we need to add), only for those related to competition management and the user itself (current user data, WCIF, manageable competitions).

**Comment by ronaldmansveld** [comment]
In that case the answer is no, the client will not need that. So server side it is then :)

**Comment by jfly** [comment]
> The main flaw of this flow is the fact that access token resides in the browser, thus being more open to stealing. On the other hand, if we are going to pass the token to the client anyway to make WCA requests directly, then I'm not sure how helpful it is to do server-side OAuth... @jfly, @coder13?

Even if we do expose the access token to the client, there's a benefit in handling the OAuth flow server side because the application secret can actually stay... secret (this is the `code` flow @jonatanklosko alluded to above). This prevents other people from building webpages that have the exact same oauth flow as wca-live.

> In that case the answer is no, the client will not need that. So server side it is then :)

@ronaldmansveld, the client is going to need a list of the user's upcoming competitions in order to build the "import competition" page (see https://balsamiq.cloud/skau0/pkzh4/rBE66). I don't have a strong opinion about whether @coder13's node server should expose this via a new api, or if the client should hit the WCA API directly. It might be cleaner to do the former...

**Comment by ronaldmansveld** [comment]
If we all agree that it's best to have the server handle the auth flow, then I opt for proxy-ing those (few) endpoints through that server. For the client it doesn't really matter if we're talking to server A or B.

There is obviously more overhead involved when proxying, but if those endpoints are not hit constantly, the difference should be necligible (sp?).

**Comment by coder13** [comment]
I added some code to handle login.
Should find a place to squeeze it into the api doc.

/auth/wca houses all the routes
/login begins the login flow and redirects the user to the wca website to login. You can pass in a query param: redirect to redirect the user back to a page in the client
/logout will log the user out.
